#!/usr/bin/env node
/**
 * dsh desktop sidecar packager.
 *
 * Assembles the Tauri sidecar: a Node runtime (>=22.19, engines of @deepseek-ai/dsh)
 * + the dsh host bundle (the dependency closure generated by build-closure.mjs),
 * renamed to the Tauri sidecar convention `dsh-host-<target-triple>[.exe]` and placed
 * under `<repo 根>/native/binaries/`. The host bundle is staged to
 * `<repo 根>/resources/app/`: the closure dir (`deepseek-harness/`) is copied there,
 * then `npm install --prefix resources/app` resolves deps — npm 模式从 registry、
 * source 模式从闭包内 file: tgz（三方依赖仍走 registry）。**局部安装，不碰全局 npm /
 * 其他项目。** The Rust shell spawns it with `--profile <设置> --no-open --port 0`
 * and reads its readiness line.
 *
 * Isolation: writes only under <repo 根>/{native/binaries,resources}.
 *
 * Usage:
 *   node scripts/package-sidecar.mjs [--triple <triple>] [--node-version <v>]
 *        [--node-bin <path>] [--dry-run]
 *   node scripts/package-sidecar.mjs [--closure <dir>] [--node-bin <path>]
 *
 * --closure <dir>: 依赖闭包目录（build-closure.mjs 生成，默认 <repo 根>/deepseek-harness）。
 *                  **两条通道统一走它**——npm 模式闭包（version specs，registry 解析）或
 *                  source 模式闭包（file: 依赖 + tgz/，本地解析）都 stage 成宿主包再
 *                  npm install；三方依赖仍走 registry。--closure 仅用于覆盖默认路径。
 * --node-bin: copy a local Node executable instead of downloading (recommended
 *             for local verification). Downloading a pinned Node archive is a
 *             CI concern (M3); the URL is printed for reference.
 */
import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, cpSync, rmSync, readdirSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { appendLedger } from './lib/ledger.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = resolve(HERE, '..')
const SRC_TAURI = join(PKG_ROOT, 'native')
const BINARIES = join(SRC_TAURI, 'binaries')
const RESOURCES = join(PKG_ROOT, 'resources') // stable host-bundle dir (M1 wires bundle.resources)

const DEFAULT_NODE_VERSION = '22.20.0' // satisfies dsh engines ^22.19.0 || >=24

/** platform-arch -> Tauri target triple metadata. */
const TRIPLES = {
  'win32-x64':    { triple: 'x86_64-pc-windows-msvc',   ext: '.exe', os: 'win',    arch: 'x64' },
  'win32-arm64':  { triple: 'aarch64-pc-windows-msvc',   ext: '.exe', os: 'win',    arch: 'arm64' },
  'darwin-x64':   { triple: 'x86_64-apple-darwin',       ext: '',    os: 'darwin', arch: 'x64' },
  'darwin-arm64': { triple: 'aarch64-apple-darwin',      ext: '',    os: 'darwin', arch: 'arm64' },
  'linux-x64':    { triple: 'x86_64-unknown-linux-gnu',  ext: '',    os: 'linux',  arch: 'x64' },
  'linux-arm64':  { triple: 'aarch64-unknown-linux-gnu', ext: '',    os: 'linux',  arch: 'arm64' },
}

function parseArgs(argv) {
  const opts = { triple: undefined, nodeVersion: DEFAULT_NODE_VERSION, nodeBin: undefined, closure: undefined, dryRun: false }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--dry-run') opts.dryRun = true
    else if (a === '--triple') opts.triple = argv[++i]
    else if (a === '--node-version') opts.nodeVersion = argv[++i]
    else if (a === '--node-bin') opts.nodeBin = argv[++i]
    else if (a === '--closure') opts.closure = argv[++i]
    else throw new Error(`unknown option: ${a}`)
  }
  return opts
}

function resolveTriple(over) {
  if (over) {
    const hit = Object.values(TRIPLES).find((t) => t.triple === over)
    if (!hit) throw new Error(`unsupported --triple ${over}`)
    return hit
  }
  const key = `${process.platform}-${process.arch}`
  const hit = TRIPLES[key]
  if (!hit) throw new Error(`unsupported platform/arch ${key}`)
  return hit
}

function sidecarName(t) {
  return `dsh-host-${t.triple}${t.ext}`
}

function nodeDistUrl(version, t) {
  const base = `https://nodejs.org/dist/v${version}/node-v${version}-${t.os}-${t.arch}`
  return t.os === 'win' ? `${base}.zip` : `${base}.tar.gz`
}

/** Quote one command-line argument that contains whitespace or quotes. */
function quoteArg(a) {
  return /[\s"]/.test(a) ? `"${a.replace(/"/g, '\\"')}"` : a
}

/**
 * Run an external command. On Windows, `.cmd` shims (pnpm) are not directly
 * spawnable, so route through `cmd /d /s /c`; args containing spaces are
 * quoted. Other platforms spawn directly.
 */
function run(cmd, args, opts) {
  console.log(`$ ${cmd} ${args.join(' ')}`)
  if (opts.dryRun) return
  const r = process.platform === 'win32'
    ? spawnSync('cmd', ['/d', '/s', '/c', [cmd, ...args].map(quoteArg).join(' ')], { stdio: 'inherit' })
    : spawnSync(cmd, args, { stdio: 'inherit' })
  if (r.error) throw new Error(`${cmd} failed to start: ${r.error.message}`)
  if (r.status !== 0) throw new Error(`${cmd} exited with ${r.status}`)
}

function ensureNodeRuntime(opts) {
  const t = resolveTriple(opts.triple)
  const out = join(BINARIES, sidecarName(t))
  if (existsSync(out)) {
    console.log(`sidecar already present: ${out}`)
    return out
  }
  if (opts.nodeBin) {
    console.log(`copying local node binary -> ${out}`)
    if (!opts.dryRun) {
      mkdirSync(BINARIES, { recursive: true })
      cpSync(opts.nodeBin, out)
    }
    return out
  }
  // M0 does not implement network download + archive extraction (needs system
  // tar on Windows; CI concern in M3). Print the intended URL for reference.
  console.log(`[download not implemented in M0] intended: ${nodeDistUrl(opts.nodeVersion, t)}`)
  console.log(`hint: pass --node-bin <node executable> to assemble without a download.`)
  throw new Error('no node runtime source: pass --node-bin or run on CI (M3 implements download)')
}

/**
 * Prune sourcemaps / TypeScript declarations from the installed host bundle.
 *
 * Why: npm's flat node_modules still contains deep .map / .d.ts files (e.g.
 * @mistralai/mistralai, @opentelemetry/*). Resolved from a long project-root
 * path they exceed Windows MAX_PATH (260), and makensis (NSIS, 32-bit, not
 * long-path-aware) aborts bundling with "failed opening file …d.ts.map".
 * These files are dev-only (sourcemaps / type declarations), never needed at
 * runtime — pruning fixes packaging and shrinks the installer.
 */
function pruneHostBundle(appDir, opts) {
  if (opts.dryRun) {
    console.log('[dry-run] would prune *.map / *.d.ts from host bundle')
    return
  }
  let removed = 0
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        walk(join(dir, entry.name))
      } else if (entry.isFile() && (entry.name.endsWith('.map') || entry.name.endsWith('.d.ts'))) {
        rmSync(join(dir, entry.name), { force: true })
        removed++
      }
    }
  }
  walk(appDir)
  console.log(`pruned ${removed} non-runtime files (*.map / *.d.ts) from host bundle`)
}

/**
 * Keep only the current platform's native binaries in the installed bundle.
 *
 * Why: npm install pulls prebuilds / optional platform packages for ALL
 * platforms (node-pty/prebuilds ships darwin/linux/win32; @img/sharp-* ships a
 * per-platform native binding plus a wasm fallback). Only the current
 * platform's copy is needed at runtime — and since the bundle is always
 * assembled on the target platform, each platform's package keeps exactly its
 * own. Dropping the rest shrinks the installer. If a platform lacks a native
 * binding (no `${platform}-${arch}` copy), the wasm fallback is kept.
 */
function pruneNativeCrossPlatform(appDir, opts) {
  // Native binaries are per-target-platform. Honor --triple when given (e.g.
  // cross-assembly), else the machine running this script — the normal flow
  // assembles on the target machine, so they coincide.
  const triple = resolveTriple(opts.triple)
  const keep = Object.entries(TRIPLES).find(([, t]) => t.triple === triple.triple)?.[0]
    ?? `${process.platform}-${process.arch}` // e.g. win32-x64
  if (opts.dryRun) {
    console.log(`[dry-run] would prune cross-platform native packages (keep ${keep})`)
    return
  }
  let removed = 0
  // node-pty: keep only this platform's prebuild (e.g. win32-x64).
  const ptyPrebuilds = join(appDir, 'node_modules', 'node-pty', 'prebuilds')
  if (existsSync(ptyPrebuilds)) {
    const hasKeep = existsSync(join(ptyPrebuilds, keep))
    for (const e of readdirSync(ptyPrebuilds, { withFileTypes: true })) {
      if (e.isDirectory() && e.name !== keep && hasKeep) {
        rmSync(join(ptyPrebuilds, e.name), { recursive: true, force: true })
        removed++
      }
    }
  }
  // @img/sharp-*: keep this platform's native binding; drop the wasm fallback
  // only when the native one is present (else sharp would lose its fallback).
  const imgDir = join(appDir, 'node_modules', '@img')
  if (existsSync(imgDir)) {
    const hasNative = existsSync(join(imgDir, `sharp-${keep}`))
    for (const e of readdirSync(imgDir, { withFileTypes: true })) {
      if (!e.isDirectory() || !e.name.startsWith('sharp')) continue
      if (e.name === `sharp-${keep}`) continue
      if (e.name === 'sharp-wasm32' && !hasNative) continue
      rmSync(join(imgDir, e.name), { recursive: true, force: true })
      removed++
    }
  }
  // Claude Agent SDK: drop the bundled native CLI package entirely (keeps the
  // ~253MB claude.exe out of the installer). dsh-subagent-claude-code resolves
  // `claude` from PATH and passes it to the SDK as `pathToClaudeCodeExecutable`
  // (verified: the SDK never uses the bundled package, and needs a real
  // executable, not a .cmd shim). Users who want the "Claude Code 子 agent"
  // feature install a real claude via scripts/fetch-claude.mjs.
  const anthropicDir = join(appDir, 'node_modules', '@anthropic-ai')
  if (existsSync(anthropicDir)) {
    for (const e of readdirSync(anthropicDir, { withFileTypes: true })) {
      if (e.isDirectory() && e.name.startsWith('claude-agent-sdk-')) {
        rmSync(join(anthropicDir, e.name), { recursive: true, force: true })
        removed++
      }
    }
  }
  // 注：codex 平台包（374M）的剪除 + patch 在独立脚本 apply-codex-shrink.mjs（可移除），不在此。
  console.log(`pruned ${removed} cross-platform native packages (keep ${keep})`)
}

/**
 * 剪掉体积巨大、且默认用不到的**可选**引擎包（与上面的跨平台裁剪不同：
 * 这里剪的是**当前平台**的包，只是因为它大得不合理）。
 *
 * `@deepseek-ai/libreoffice-kit-<platform>`（win32-x64 的 `program/` 约 330MB，
 * 压缩后安装包 +87MB）是上游 0.1.6 起为 office 文档转 PDF
 * （`@deepseek-ai/dsh-document-office-to-pdf`）捆绑的整套 LibreOffice 引擎，
 * 随 web profile 默认装进来。只剪平台包，保留主包 `@deepseek-ai/libreoffice-kit`
 * （~800KB，上游 `import` 它）。
 *
 * 缺失时 `createConverter` 以 `ConversionError: unavailable` **优雅降级**
 * （宿主照常启动，已实测），并由 `scripts/fetch-libreoffice.mjs` 在首次启动时
 * 按需补装回 node_modules 原位（引擎路径由上游内部解析，无 env 可覆盖，
 * 故不能像 codex 那样装到 ~/.dsh）。
 *
 * 不需要该功能 / 上游改为按需下载时：删除本函数与其调用即可（另见
 * fetch-libreoffice.mjs 头部的移除点清单）。
 */
function pruneOptionalBulk(appDir, opts) {
  const dshDir = join(appDir, 'node_modules', '@deepseek-ai')
  if (!existsSync(dshDir)) return
  // 只匹配平台包（libreoffice-kit-win32-x64…），不碰主包 libreoffice-kit。
  const targets = readdirSync(dshDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name.startsWith('libreoffice-kit-'))
  if (!targets.length) return
  if (opts.dryRun) {
    for (const t of targets) console.log(`[dry-run] would prune ${t.name}`)
    return
  }
  for (const t of targets) rmSync(join(dshDir, t.name), { recursive: true, force: true })
  console.log(`pruned ${targets.length} optional engine package(s) (libreoffice-kit-*)`)
}

/** 打包时兜底记录 ledger：读闭包 dsh 版本 + 推断 channel 写入（merge 保留 build-closure 富条目）。 */
function recordLedger(hostSource) {
  try {
    const closure = JSON.parse(readFileSync(join(hostSource, 'package.json'), 'utf8'))
    const app = JSON.parse(readFileSync(join(PKG_ROOT, 'package.json'), 'utf8'))
    appendLedger({
      channel: closure.overrides ? 'source' : 'npm',
      appVersion: app.version,
      appBuiltAt: new Date().toISOString().slice(0, 10),
      dshVersion: closure.version,
    })
  } catch (e) {
    console.log(`[sidecar] 记录 ledger 失败（不影响打包）: ${e.message}`)
  }
}

function prepareHostBundle(opts) {
  const appDir = join(RESOURCES, 'app')
  // 两条通道统一：stage 依赖闭包目录（默认 <repo 根>/deepseek-harness，--closure 可覆盖路径）。
  const hostSource = resolve(join(HERE, '..', opts.closure ?? 'deepseek-harness'))
  if (!existsSync(join(hostSource, 'package.json'))) {
    throw new Error(`闭包目录缺少 package.json: ${hostSource}（先运行 build-closure.mjs）`)
  }
  console.log(`installing host deps (npm, flat) -> ${appDir}  [closure: ${hostSource}]`)
  if (!opts.dryRun) {
    rmSync(appDir, { recursive: true, force: true })
    mkdirSync(appDir, { recursive: true })
    cpSync(hostSource, appDir, { recursive: true })
  }
  // npm produces a flat, self-contained node_modules (no .pnpm store) — pnpm's
  // isolated layout (.pnpm hash dirs + junctions) exceeds Windows MAX_PATH(260)
  // and breaks makensis/NSIS. npm flat is far shorter, but deep .map/.d.ts
  // files + a long project root can still cross 260, so prune right after
  // install (see pruneHostBundle). Native modules (node-pty/koffi) compile via
  // npm install scripts.
  run('npm', ['install', '--omit=dev', '--no-audit', '--no-fund', '--prefix', appDir.replace(/\\/g, '/')], opts)
  // Dev-only sourcemaps / type declarations would exceed MAX_PATH when bundled
  // (see pruneHostBundle) — remove them before tauri build packages this dir.
  pruneHostBundle(appDir, opts)
  // Keep only this platform's native binaries (node-pty prebuilds, @img/sharp).
  pruneNativeCrossPlatform(appDir, opts)
  // 剪掉可选的巨型引擎包（LibreOffice，330MB）：首次启动由 fetch-libreoffice.mjs 按需补装。
  pruneOptionalBulk(appDir, opts)
  // codex 瘦身 + patch（可移除：上游支持 codex PATH/CODEX_BIN 后删此行，见 apply-codex-shrink.mjs 头部）。
  run('node', ['scripts/apply-codex-shrink.mjs', appDir], opts)
  // 清理闭包安装源：file: tgz 已解包进 node_modules，归档是死重，且会被 bundle.resources
  // 整体打进安装包（实测 release/dsh-host/app/tgz 8.1M）——npm install 后删掉省安装包体积。
  if (!opts.dryRun) {
    rmSync(join(appDir, 'tgz'), { recursive: true, force: true })
    console.log('pruned closure install sources (resources/app/tgz)')
  } else {
    console.log('[dry-run] would prune resources/app/tgz (closure install sources)')
  }
  // The host lives under the installed dependency, not the bundle root.
  const bin = join(appDir, 'node_modules', '@deepseek-ai', 'dsh', 'lib', 'bin.js')
  if (!opts.dryRun && !existsSync(bin)) {
    throw new Error(`installed host missing ${bin}`)
  }
  // 打包时兜底记录 ledger（任何打包路径都会走到这里，不依赖 build-closure 先跑）。
  if (!opts.dryRun) recordLedger(hostSource)
  return bin
}

function main() {
  const opts = parseArgs(process.argv.slice(2))
  const t = resolveTriple(opts.triple)
  const name = sidecarName(t)
  console.log(`[deepseek-harness-desktop sidecar] target=${t.triple} node=${opts.nodeVersion} dryRun=${opts.dryRun}`)
  if (opts.dryRun) {
    console.log('-- dry-run: steps below are NOT executed --')
    console.log(`  sidecar  -> ${join(BINARIES, name)}`)
    console.log(`  hostBundle-> ${join(RESOURCES, 'app')}  (closure: ${opts.closure ?? 'deepseek-harness'})`)
    console.log(`  node runtime: ${opts.nodeBin ?? nodeDistUrl(opts.nodeVersion, t)}`)
    return 0
  }
  rmSync(RESOURCES, { recursive: true, force: true })
  mkdirSync(RESOURCES, { recursive: true })
  ensureNodeRuntime(opts)
  prepareHostBundle(opts)
  console.log(`[deepseek-harness-desktop sidecar] done. sidecar=${join(BINARIES, name)} hostBundle=${join(RESOURCES, 'app')}`)
  return 0
}

process.exitCode = main()
